# Generated by Django 2.1.1 on 2018-11-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.TextField(default='', verbose_name='Resposta'),
        ),
    ]
