# Generated by Django 2.1.1 on 2018-11-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20181102_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='Identificador'),
        ),
    ]
